### ISSUE TITLE
Support for additional options in pip

### ISSUE THREAD

**Issue by victorock** [geerlingguy/ansible-role-pip#13]
Support for the following:
- pip_state: Useful when needed to specify the state of the pip package itself (Ex: `latest`)
- extra_args Useful when modules must be upgraded (Ex: `--upgrade`)
- executable Useful when multiple pip version are installed (Ex: `pip3`)

**Comment by magick93** [comment]
And `--trusted-host`, for those of us working being corporate firewalls.

**Comment by magick93** [comment]
@victorock - I tried your fork to test the support for `extra_args`, specifically I ran:

```
- name: Install pip and pip packages
    include_role:
      name: victorock.pip
    vars:
      pip_executable: pip
      pip_package: "{{ item }}"
      pip_install_packages: 
        - requests
        - kubernetes
      ansible_become: yes
      extra_args: '--upgrade'
    loop: 
      - python-pip
      - python3-pip
```

But it didnt upgrade pip.
