### ISSUE TITLE
Support installing packages from requirements.txt

### ISSUE THREAD

**Issue by twistedFantasy** [geerlingguy/ansible-role-pip#21]
Now there is an option to install packages with `pip_install_packages`, but it will be great if this role can also support installing packages from different locations of `requirements.txt`, something like this:
```
---
- name: Install pip3 files
  pip:
    requirements: "{{ item }}/requirements.txt"
  with_items: "{{ dirs }}"
``` 

What do you think? Any reason why we shouldn't do it?
