### ISSUE TITLE
PIP install should not set ansible PPA

### ISSUE THREAD

**Issue by ptr727** [geerlingguy/ansible-role-pip#31]
Ubuntu 20.04 LTS there is no ppa:ansible/ansible repo.
Installing the latest ansible on 20.04 must be done with PIP.
The task always tries to add the PPA, and always fails.
```yaml
- name: Add ansible repository.
  apt_repository: repo='ppa:ansible/ansible'
```

Suggest that when installing using PIP no repo is registered.

E.g.
``` yaml
- name: Set up Ansible on Ubuntu.
  include_tasks: setup-Ubuntu.yml
  when: ansible_distribution == 'Ubuntu' # AND ansible_install_method != 'pip'
```
