### ISSUE TITLE
Be able to choose state for each package

### ISSUE THREAD

**Issue by kakawait** [geerlingguy/ansible-role-pip#4]
Will be allow us to _upgrade_ or uninstall pip packages.

Today there is no state, so fallback to default `present`.

like 

```
pip_install_packages:
  # Specify names and versions.
  - name: docker
    version: "1.2.3"
  - name: awscli
    version: "1.11.91"
    state: forcereinstall
  # Or specify bare packages to get the latest release.
  - docker
    state: latest
  - awscli
    state: absent
```
