### ISSUE TITLE
How to install the latest 21.3.1 version of pip, and not 9.0.1 - cant install docker-compose on Ubuntu 18.04

### ISSUE THREAD

**Issue by elburro1887** [geerlingguy/ansible-role-pip#47]
I'm trying to use this role to install the pip release of docker-compose on an Ubuntu 18.04 machine, my playbook:

```
- hosts: all
  gather_facts: no
  become: yes

  vars:
    pip_package: python3-pip
    pip_install_packages:
      - name: docker
      - name: docker-compose==1.29.2

  roles:
    - geerlingguy.pip
```

Problem is, the role installs the old pip 9.0.1, which results in the following error when trying to install docker-compose:
`ModuleNotFoundError: No module named 'setuptools_rust'`

If i upgrade pip manually on the server to 21.3.1, the playbook works.

How can we get the latest version of pip from the role? Or is that not supported?

**Comment by Aryess** [comment]
@elburro1887 I had the same issue, resolved by explicitely adding pip to the packages

```
    - role: geerlingguy.pip
      pip_install_packages:
        - name: pip
          version: "21.2.3"
        - docker
        - docker-compose
```
