### ISSUE TITLE
No package matching 'python3-pip' is available

### ISSUE THREAD

**Issue by dbrennand** [geerlingguy/ansible-role-pip#49]
# Summary

Running this role on a newly provisioned server failed with the error:

```
FAILED! => {"changed": false, "msg": "No package matching 'python3-pip' is available"}
```

Found a similar issue mentioned in https://github.com/leesoh/ansible-role-pipenv/issues/1

Fix is to add `update_cache` to the `Ensure Pip is installed.` task. PR to follow.

**Comment by geerlingguy** [comment]
I typically control caches on the play level, and not in roles (since every role that touches `apt` would have to update cache, and deal with lifetime/idempotency issues).

**Comment by boite** [comment]
This issue will arise when the managed host's OS Package Manager cache is empty.  For example, `apt update` had not yet been run.  The easiest fix is to run something like the following task, early in your play:

```yaml
- name: Populate Apt's Cache with package definitions to avoid "no such package" errors
  ansible.builtin.apt:
    update_cache: true
```

**Comment by ChristopherJHart** [comment]
To build off of @boite's comment, if you are using the `geerlingguy.pip` role in a `site.yaml` or `site.yml` playbook, you will most likely need to modify your `site.yaml` playbook to something similar to the following:
```yaml
---
- name: Populate Apt's Cache with package definitions to avoid "no such package" errors
  hosts: servers
  ansible.builtin.apt:
    update_cache: true
- hosts: servers
  roles:
    - geerlingguy.pip
```
Note that the `ansible.builtin.apt` module may need privilege escalation via `become: true` as shown below, depending on what credentials you are using to access your hosts.
```yaml
- name: Populate Apt's Cache with package definitions to avoid "no such package" errors
  hosts: servers
  ansible.builtin.apt:
    update_cache: true
  become: true
- hosts: servers
  roles:
    - geerlingguy.pip
```
