### ISSUE TITLE
Parameters are mutually exclusive: executable|virtualenv

### ISSUE THREAD

**Issue by dmotte** [geerlingguy/ansible-role-pip#55]
Hi. First of all, thanks a lot for this role :wink: it's very useful

Using `geerlingguy.pip` role version: **2.2.0**

Using Ansible core version **2.14.2**

My Ansible task:

```yaml
- name: Install some pip packages
  ansible.builtin.include_role: { name: geerlingguy.pip }
  vars:
    ansible_become: true
    pip_install_packages:
      - name: glances==3.*
        virtualenv: /opt/venv01
```

What I get:

```
TASK [geerlingguy.pip : Ensure pip_install_packages are installed.] ************
failed: [default] (item={'name': 'glances==3.*', 'virtualenv': '/opt/venv01'}) => {"ansible_loop_var": "item", "changed": false, "item": {"name": "glances==3.*", "virtualenv": "/opt/venv01"}, "msg": "parameters are mutually exclusive: executable|virtualenv"}
```

I believe the error is at: https://github.com/geerlingguy/ansible-role-pip/blob/master/tasks/main.yml#L14

Maybe the `executable` task parameter should be changed to `"{{ pip_executable | default(omit) }}"` and the `pip_executable` variable should be unset by default? Don't know, just proposing something

**Comment by 5t0ne** [comment]
Would like to reopen this as that's still a problem.

Using this: 
```
- role: geerlingguy.pip
      vars:
        pip_install_packages:
          - name: docker
            virtualenv: /opt/python/venv
```

Still gives that message:
`ASK [geerlingguy.pip : Ensure pip_install_packages are installed.] *******************************************************************************************************************
failed: [urbackup] (item={'name': 'docker', 'virtualenv': '/opt/python/venv'}) => {"ansible_loop_var": "item", "changed": false, "item": {"name": "docker", "virtualenv": "/opt/python/venv"}, "msg": "parameters are mutually exclusive: executable|virtualenv"}`

Could the proposed fix pls be implemented?
