### ISSUE TITLE
Failed to install docker on Ubuntu 24.04

### ISSUE THREAD

**Issue by wwwlaomao** [geerlingguy/ansible-role-pip#66]
* Host OS: Ubuntu 24.04
* geerlingguy.pip version 3.0.3
* The playbook excerpt

```
    - role: geerlingguy.pip
      vars:
        pip_install_packages:
          - name: docker
      become: true
```

* Error message

```
failed: [playground] (item={'name': 'docker'}) => {"ansible_loop_var": "item", "changed": false, "cmd": ["/usr/bin/pip3", "install", "docker"], "item": {"name": "docker"}, "msg": "\n:stderr: error: externally-managed-environment\n\n× This environment is externally managed\n╰─> To install Python packages system-wide, try apt install\n    python3-xyz, where xyz is the package you are trying to\n    install.\n    \n    If you wish to install a non-Debian-packaged Python package,\n    create a virtual environment using python3 -m venv path/to/venv.\n    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make\n    sure you have python3-full installed.\n    \n    If you wish to install a non-Debian packaged Python application,\n    it may be easiest to use pipx install xyz, which will manage a\n    virtual environment for you. Make sure you have pipx installed.\n    \n    See /usr/share/doc/python3.12/README.venv for more information.\n\nnote: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.\nhint: See PEP 668 for the detailed specification.\n"}
```

**Comment by geerlingguy** [comment]
See: https://github.com/geerlingguy/ansible-role-pip/issues/57

**Comment by ShaneMcC** [comment]
> See: #57

Looks like the fix in that commit specifically deletes the file for python3.11 - but 24.04 uses python3.12, and it only does it on debian12  not other versions.

@geerlingguy - Any chance changing this to something more generic?

Adding:
```yaml
- name: Remove EXTERNALLY-MANAGED
  ansible.builtin.file:
    path: /usr/lib/python3.{{ ansible_python.version.minor }}/EXTERNALLY-MANAGED
    state: absent
```

Under the `- name: Ensure Pip is installed.` task and removing the debian12.yml and the task that includes it seems like it fixes this issue and also #67 and the original #57 ?

Would you accept a PR to fix this
