### ISSUE TITLE
TASK [geerlingguy.pip : Ensure Pip is installed.] re-installs EXTERNALLY-MANAGED

### ISSUE THREAD

**Issue by miquelbonastreguillen** [geerlingguy/ansible-role-pip#67]
The first run of my playbooks using your role geerlingguy.pip (on Debian 12), fails with the well known message "This environment is externally managed".

On a second run of my playbooks, without changes, all goes well.

After some debugging, I've found that the task "Ensure Pip is installed" re-installs the EXTERNALLY-MANAGED file:

```
- name: Ensure Pip is installed.
  package:
    name: "{{ pip_package }}"
    state: present
```

Changing the order of the tasks solves the problem:

```
- name: Ensure Pip is installed.
  package:
    name: "{{ pip_package }}"
    state: present

- name: Remove externally managed from Debian 12
  ansible.builtin.import_tasks: debian12.yml
  when:
    - ansible_distribution == "Debian"
    - ansible_distribution_major_version|int >= 12
```

It seams that "python3-pip" depends on "python3" which depends on "libpython3.11-stdlib" and this is the owner of the /usr/lib/python3.11/EXTERNALLY-MANAGED file. So instal·ling python3-pip, for some reason, reinstalls the deleted file.
