### ISSUE TITLE
Does this role install python3 as well?

### ISSUE THREAD

**Issue by 030** [geerlingguy/ansible-role-pip#8]

**Comment by josdotso** [comment]
Seems to me it should expose the executable var to really support python3 well:

http://docs.ansible.com/ansible/latest/pip_module.html

**Comment by dzhus** [comment]
@josdotso Isn't this enough:

```
    - role: geerlingguy.pip
      pip_package: python3-pip
```

?

**Comment by michaelpporter** [comment]
It does not seem to be for me

```yml
pip_package: python3-pip
pip_install_packages:
  - certbot-dns-cloudflare
```
